name: Documentation
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0.
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev --frozen

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: uv pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

      - run: uv run mkdocs gh-deploy --force -f demo-mkdocs/mkdocs.yml
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 
  GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
