name: Scheduled Unit Tests
# Controls when the action will run.
# Every week "At 07:17 on Sunday."
# See https://crontab.guru/#17_7_*_*_7

# This way we know for sure package will keep working with
# potential new downstream updates
on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * 0"

jobs:
  run:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests -m "not e2e"
